spring.application.name=oauth2client
spring.security.oauth2.client.registration.google.client-id=457649372379-3ca86sd1ht51oqejcjbj4ol8ubeb3i2c.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile
