spring.application.name=roleaccess
spring.datasource.url=jdbc:mysql://localhost:3306/roleaccessdb
spring.datasource.username=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=disabled